### ISSUE TITLE
practicaARCHITEC

### ISSUE THREAD

**Issue by DaisyOrtiz2** [SistemasTecTlaxiaco/actividad-3-practica-architect-DaisyOrtiz2#1]
[practica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-DaisyOrtiz2/files/12553850/practica.pdf)

**Comment by isaireyesp1** [comment]
Portada : 22
Procedimiento : 25
Figuras, ilustraciones y fotografías.: 25
Resultados y conclusiones :22
calificacion : 94 = 18.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
